import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// Local font example
const Clarkson = localFont({
	src: [
		{
			path: "../public/fonts/Clarkson-Light.otf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../public/fonts/Clarkson-BookProduct.otf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/Clarkson-Medium.otf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/Clarkson-Semibold.otf",
			weight: "600",
			style: "normal",
		},
	],
	variable: "--font-Clarkson",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${Clarkson.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
